services:
  db:
    image: postgres:12.1-alpine
    container_name: pleroma_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pleroma"]
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: CHANGEME
      POSTGRES_DB: pleroma
    volumes:
      - ./blog/postgres:/var/lib/postgresql/data

  web:
    container_name: pleroma_web
    build:
      context: blog
      args:
        - "UID=1000"
        - "GID=1000"
        - "PLEROMA_VER=${PLEROMA_VERSION}"
    image: pleroma #Note: THIS DOES NOT PULL THE IMAGE; This names the image in the local storage
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider --proxy=off localhost:4000 || exit 1",
        ]
    restart: unless-stopped
    volumes:
      - ./uploads:/var/lib/pleroma/uploads
      - ./static:/var/lib/pleroma/static
      - ./config.exs:/etc/pleroma/config.exs:ro
    environment:
      DOMAIN: mastodon.blizzard.systems
      INSTANCE_NAME: Pleroma
      ADMIN_EMAIL: blizzardfinnegan@gmail.com
      NOTIFY_EMAIL: blizzardfinnegan@gmail.com
      DB_USER: pleroma
      DB_PASS: CHANGEME
      DB_NAME: pleroma
    depends_on:
      - db
