services:
  mc:
    image: itzg/minecraft-server
    container_name: "minecraft"
    environment:
      - EULA=true
      - MEMORY=8G
      - ENABLE_ROLLING_LOGS=true
      - VERSION=1.20.4
      - DIFFUCULTY=normal
      - FORCE_GAMEMODE=true
      - SNOOPER_ENABLED=false
      - MODE=survivor
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
