route:
  group_by: ['alertname','severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'discord'
  routes:
    - reciever: 'email'
      matchers:
        - severity="info"
    - reciever: 'all'
      matchers:
        - severity="critical"
receivers:
  - name: 'all'
    discord_configs:
      - webhook_url: DISCORD_WEBHOOK_URL
    email_configs:
      - to: blizzardfinnegan@gmail.com
        from: blizzardfinnegan@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: "blizzardfinnegan@gmail.com"
        auth_identity: "blizzardfinnegan@gmail.com"
        auth_password: APP_PASSWORD 
  - name: 'discord'
    discord_configs:
      - webhook_url: DISCORD_WEBHOOK_URL
  - name: "email"
    email_configs:
      - to: blizzardfinnegan@gmail.com
        from: blizzardfinnegan@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: "blizzardfinnegan@gmail.com"
        auth_identity: "blizzardfinnegan@gmail.com"
        auth_password: APP_PASSWORD

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
